### PR TITLE
Fix musictypeLoad() that was setting XBRZ instead of music type as intended, and use SDL2 HW scaling instead of software scaling when XBRZ is not used.

### PR DESCRIPTION
**Pull request by vanfanel**

### CODE REVIEW

**Comment by vanfanel** [comment]
@ptitSeb SDL2 offers HW scaling so, when XBRZ is not requested, HW scaling should be used.

Also, I have removed the forced screenScale in main.c, it makes no sense as that's already being done in sdl2/graphics.c if SW rendering is used (for HW rendering, fullscreen size with aspect ratio correction is used instead).

Also, corrected musictypeLoad() which was erroneously setting XBRZ.

**Comment by ptitSeb** [comment]
Nice, thanks.

(all the scalling stuff was there because SDL1 was the 1st port.. Than I added an SDL2 port by basicaly copy/paste all SDL1 logic and adapting to SDL2. But I agree, HW scalling is much better).

**Comment by vanfanel** [comment]
@ptitSeb I am glad that you like it! :)
I can go even further and remove all SW scaling from SDL2, if you want: that would mean losing software-driven XBRZ and getting hardware-accelerated bilinear interpolation instead. What about that?
I am all against software scaling as you can see :D

**Comment by ptitSeb** [comment]
No, I like to keep xbrz, some may prefer that.
I don't like much software sclling, but in the case of HCL, it's "offline", the scalling is done at load time and not in real time. So it takes just a bit longer to lad, but than there is no added delay when playing.

**Comment by vanfanel** [comment]
@ptitSeb This PR just improves animation in SDL2, it keeps software scaling intact.

**Comment by ptitSeb** [comment]
I know, no pb here.

**Comment by vanfanel** [comment]
@ptitSeb Thanks! :)

**Pull request merged**
